apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kcu0af1yn-go 
  janus-idp.io/tekton: kcu0af1yn-go
  backstage.io/kubernetes-id: kcu0af1yn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kcu0af1yn-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml