apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kcu0af1yn-go
  janus-idp.io/tekton: kcu0af1yn-go
  backstage.io/kubernetes-id: kcu0af1yn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kcu0af1yn-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
