apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kcu0af1yn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kcu0af1yn-go 
  name: kcu0af1yn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kcu0af1yn-go 
